# Omakase Ruby styling for Rails
# inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

require:
  - rubocop-rails
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'public/**/*'
    - 'config/environments/*'
    - 'config/initializers/*'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/**/*'
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/*'

Rails/FilePath:
  EnforcedStyle: arguments

Style/FetchEnvVar:
  Enabled: false

Rails/OutputSafety:
  Enabled: false
