version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      ASSET_HOST: "http://localhost"
      NODE_ENV: "production"
    volumes:
      - ./.yarnrc:/app/.yarnrc
      - rails_public:/app/public
    networks:
      - web

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.local.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.ssl:/etc/nginx/ssl:ro
      - rails_public:/app/public:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  rails_public:
