version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      ASSET_HOST: "https://www.istanbulmerkeztesisat.com"
      NODE_ENV: "production"
      RACK_TIMEOUT_SERVICE_TIMEOUT: 600
    volumes:
      - public_assets:/app/public
    networks:
      - app_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - public_assets:/app/public
      - ./tmp:/app/tmp
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_network
    depends_on:
      - web
    restart: unless-stopped

volumes:
  public_assets:

networks:
  app_network:
    driver: bridge 