version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - rails_public:/app/public
      - rails_tmp:/app/tmp
      - rails_log:/app/log
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      ASSET_HOST: "https://www.istanbulmerkeztesisat.com"
    ports:
      - "3000:3000"
    networks:
      - web

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - rails_public:/app/public:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  rails_public:
  rails_tmp:
  rails_log: 