version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    restart: always
    env_file:
      - .env
    volumes:
      - rails_public:/app/public
      - rails_tmp:/app/tmp
      - rails_log:/app/log
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
      ASSET_HOST: "https://www.istanbulmerkeztesisat.com"
      NODE_ENV: "production"
      YARN_PRODUCTION: "true"
      NODE_OPTIONS: "--max_old_space_size=4096"
    ports:
      - "3000:3000"
    networks:
      - web

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - rails_public:/app/public:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  rails_public:
    name: service_web_rails_public
  rails_tmp:
    name: service_web_rails_tmp
  rails_log:
    name: service_web_rails_log 