default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: service_web_development

test:
  adapter: postgresql
  encoding: unicode
  database: istanbulmerkeztesisat_test
  pool: 5
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>

production:
  <<: *default
  url: postgresql://postgres:mJsYumNSQVZVQJjXPgXmiLvXqcYgvCHb@monorail.proxy.rlwy.net:35428/railway 