default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: service_web_development

test:
  <<: *default
  database: service_web_test

production:
  <<: *default
  url: postgresql://postgres:mJsYumNSQVZVQJjXPgXmiLvXqcYgvCHb@monorail.proxy.rlwy.net:35428/railway 