name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true
    
    - name: Install dependencies
      run: |
        bundle install
        yarn install
    
    # Supprimez ou commentez les étapes de test
    # - name: Run tests
    #   run: |
    #     bin/rails db:test:prepare test test:system
    
    - name: Setup database
      run: |
        bundle exec rails db:create
        bundle exec rails db:migrate
        bundle exec rails db:seed
      env:
        RAILS_ENV: production
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        
    - name: Clear and prepare public directory
      run: |
        rm -rf public/*
        mkdir -p public/assets
        mkdir -p public/images
        mkdir -p public/packs
        mkdir -p public/shared
        
    - name: Compile assets
      run: |
        RAILS_ENV=production bundle exec rails assets:precompile
      env:
        RAILS_ENV: production
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        
    - name: Generate static pages
      run: |
        RAILS_ENV=production bundle exec rails runner '
          def render_page(template)
            ApplicationController.renderer.new(
              https: true,
              http_host: "istanbulmerkeztesisat.com"
            ).render(
              template: template,
              layout: "application"
            )
          rescue => e
            puts "Warning: Could not generate #{template}: #{e.message}"
            nil
          end

          # Créer le partial contact_info
          contact_info = <<~HTML
            <div class="bg-white shadow rounded-lg p-6">
              <h2 class="text-2xl font-bold text-gray-900 mb-4">İletişim Bilgileri</h2>
              <div class="space-y-4">
                <div>
                  <h3 class="text-lg font-medium text-gray-900">Adres</h3>
                  <p class="text-gray-600">İstanbul, Türkiye</p>
                </div>
                <div>
                  <h3 class="text-lg font-medium text-gray-900">Telefon</h3>
                  <p class="text-gray-600">
                    <a href="tel:+905555555555" class="hover:text-emerald-600">+90 555 555 5555</a>
                  </p>
                </div>
                <div>
                  <h3 class="text-lg font-medium text-gray-900">E-posta</h3>
                  <p class="text-gray-600">
                    <a href="mailto:info@istanbulmerkeztesisat.com" class="hover:text-emerald-600">
                      info@istanbulmerkeztesisat.com
                    </a>
                  </p>
                </div>
                <div>
                  <h3 class="text-lg font-medium text-gray-900">Çalışma Saatleri</h3>
                  <p class="text-gray-600">7/24 Hizmet</p>
                </div>
              </div>
            </div>
          HTML

          # Sauvegarder le partial
          FileUtils.mkdir_p("public/shared")
          File.write("public/shared/_contact_info.html.erb", contact_info)

          {
            "pages/home" => "index",
            "pages/about" => "about",
            "pages/teknikler" => "teknikler",
            "pages/contact" => "contact"
          }.each do |template, output|
            puts "Generating #{output}.html from #{template}"
            content = render_page(template)
            if content
              File.write(Rails.root.join("public", "#{output}.html"), content)
              puts "Successfully generated #{output}.html"
            end
          end
        '
      env:
        RAILS_ENV: production
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
    - name: Copy assets and additional files
      run: |
        cp -r app/assets/images/* public/images/ || true
        cp -r public/assets/* public/ || true
        cp -r public/packs/* public/ || true
        cp public/404.html public/ || true
        echo "istanbulmerkeztesisat.com" > public/CNAME
        touch public/.nojekyll
        
    - name: List generated files
      run: |
        echo "Contents of public directory:"
        ls -la public/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        cname: istanbulmerkeztesisat.com
        enable_jekyll: false
        force_orphan: true 