name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true
    
    - name: Install dependencies
      run: |
        bundle install
        yarn install
    
    - name: Setup database
      run: |
        bundle exec rails db:create
        bundle exec rails db:migrate
        bundle exec rails db:seed
      env:
        RAILS_ENV: production
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        
    - name: Prepare public directory
      run: |
        rm -rf public/*
        mkdir -p public/assets
        mkdir -p public/images
        
    - name: Compile assets
      run: |
        RAILS_ENV=production bundle exec rails assets:precompile
      env:
        RAILS_ENV: production
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        
    - name: Generate static pages
      run: |
        RAILS_ENV=production bundle exec rails runner "['home', 'about', 'services'].each { |page| File.write(Rails.root.join('public', \"#{page}.html\"), ApplicationController.renderer.render(template: \"pages/#{page}\", layout: 'application')) }"
      env:
        RAILS_ENV: production
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
    - name: Copy additional files
      run: |
        cp public/404.html public/
        echo "istanbulmerkeztesisat.com" > public/CNAME
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        cname: istanbulmerkeztesisat.com
        enable_jekyll: false
        force_orphan: true 